name: Pull request

on:
  pull_request:

permissions:
  contents: read

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log it
        run: node -e 'console.log(process.env)'
        env:
          LL_GH_REF: ${{ github.ref }}
          LL_GH_REF_NAME: ${{ github.ref_name }}
          LL_GH_BASE_REF: ${{ github.base_ref }}
          LL_GH_HEAD_REF: ${{ github.head_ref }}
          LL_GH_ACTOR: ${{ github.actor }}
          LL_GH_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
          LL_GH_ACTION_REF: ${{ github.action_ref }}
          LL_GH_WORKFLOW: ${{ github.workflow }}
          LL_GH_EVENT_NAME: ${{ github.event_name }}
          LL_GH_REPOSITORY: ${{ github.repository }}
          LL_GH_EVENT_ACTION: ${{ github.event.action }}
          LL_GH_EVENT_REVIEW_STATE: ${{ github.event.review.state }}
          LL_GH_EVENT_REVIEW_USER_NAME: ${{ github.event.review.user.name }}
          LL_GH_EVENT_PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          LL_GH_EVENT_PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          LL_GH_EVENT_PR_NUMBER: ${{ github.event.pull_request.number }}
